apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: yet-another-hello-world
  labels:
    cloud.googleapis.com/location: us-central1
    app: yet-another-hello-world
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: nchan009@gmail.com
    serving.knative.dev/lastModifier: nchan009@gmail.com
    client.knative.dev/user-image: gcr.io/dev-project-311801/yet-another-hello-world:dev
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        app: yet-another-hello-world
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 867746492312-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/dev-project-311801/yet-another-hello-world:dev
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
