name: build-push-image

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initialise Docker Daemon
        run: |
          dockerd -H unix:///var/run/docker.sock 
      
      - name: Run Docker Build
        run: |
          docker build --build-arg MAVEN_BUILD=maven:3.6.3-jdk-11-slim --build-arg MYAPP_IMAGE=openjdk:11-jdk-slim -t localhost:5000/hello-world:latest .

      - name: Push Docker Image
        run: |
          docker push localhost:5000/hello-world
