name: build-push-image

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: MYAPP_IMAGE=openjdk:11-jdk-slim
          build-args: MAVEN_BUILD=maven:3.6.3-jdk-11-slim
          push: true
          tags: user/app:latest