name: build-push-image

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Initialise Docker
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:buildx-stable-1-rootless
          
      - name: Docker Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            MAVEN_BUILD=maven:3.6.3-jdk-11-slim
            MYAPP_IMAGE=openjdk:11-jdk-slim
          push: true
          tags: localhost:5000/hello-world:latest
