name: gcp-build-push

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY_USER: _json_key
  IMAGE_REGISTRY: gcr.io/dev-project-311801
  REGISTRY_PASSWORD: ${{ secrets.GCP_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test with Maven
        run: mvn test -Punittest -f pom.xml

      - name: Build with Maven
        run: mvn -B package -DskipTests -f pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER}}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: .
          push: true
          tags: ${{ env.IMAGE_REGISTRY }}/yet-another-hello-world:dev

      - name: Check Code Coverage
        run: mvn -B verify -f pom.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.CLOUD_RUN_KEY }}'

      - id: 'deploy'
        name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          metadata: gcp-service.yaml

      - name: 'Run Integration Test'
        run: 'mvn test -Pintegration -DGCP_HELLO_WORLD_URL=${{ steps.deploy.outputs.url }}'

