name: quay-build-push

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY_USER: ${{ secrets.QUAY_USERNAME }}
  IMAGE_REGISTRY: quay.io
  REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.REGISTRY_USER}}
          password: ${{ env.REGISTRY_PASSWORD }}
          
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            MAVEN_BUILD=maven:3.6.3-jdk-11-slim
            MYAPP_IMAGE=openjdk:11-jdk-slim
          push: true
          tags: naythanc/yet-another-hello-world:latest
