name: reg-build-push

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY_USER: registry
  IMAGE_REGISTRY: registry.naythanc.dev
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER}}
          password: ${{ env.REGISTRY_PASSWORD }}
          
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |
            MAVEN_BUILD=maven:3.6.3-jdk-11-slim
            MYAPP_IMAGE=registry.access.redhat.com/ubi8/openjdk-11:1.10
          push: true
          tags: ${{ env.IMAGE_REGISTRY }}/yet-another-hello-world:latest
